Convert Water Meter values
frenck/python-toonapi pull request #1
Opened 2020-07-20 14:32 UTC by tizzen33

Hi Frenck

This pull request converts water usage sensors to more readable values:

- Average: liters/hour to liters/minute
- Current: liters/hour to liters/minute
- Day Average: cm3 to m3
- Day Usage: cm3 to m3
- Meter: cm3 to m3

I also added Daily Water Cost which is also sent by the API.

2020-07-20 19:19 UTC, frenck commented on toonapi/models.py
> +        self.day_usage = process_data(data, "dayUsage", self.day_usage, convert_m3)
Thought: For day usage, the M3 might be too big? Considering the average water usage for a household in NL to be somewhere 90-150M3 a year?

2020-07-20 20:49 UTC, tizzen33 commented on toonapi/models.py
> +        self.day_usage = process_data(data, "dayUsage", self.day_usage, convert_m3)
True, but I tought I'd follow the same unit as the Boxx display.

2020-07-20 21:56 UTC, frenck commented on toonapi/models.py
> +        self.day_usage = process_data(data, "dayUsage", self.day_usage, convert_m3)
Ok that makes sense 👍

2020-07-20 21:59 UTC, frenck requested changes
Ok, in general 👍  Great job!

One small change is still needed. The types of the class variables of `WaterUsage` are not correct now anymore. `average`, `current`, `day_average`, `day_usage` and `meter` are now a `float` because of the calculations.

The typehints for those are still `int`.

2020-07-21 09:25 UTC, frenck approved these changes
Awesome! I will patch up a package release today 👍

2020-07-21 09:32 UTC, tizzen33 commented
Ok, great!

2020-08-04 17:54 UTC, merged